### ISSUE TITLE
configure_ib task fails - can't find handler

### ISSUE THREAD

**Issue by sjpb** [stackhpc/p3-appliances#89]
command:

`ansible-playbook --vault-password-file monasca-secrets -e @config/steveb.yml -i ansible/inventory-steveb ansible/cluster-infra-configure.yml`

error:
```
...
TASK [configure_ib : Ensure kernel modules persist]
...
ERROR! The requested handler 'Reset interface' was not found in either the main handlers list nor in the listening handlers list
```

However in `p3-appliances/ansible/roles/configure_ib/handlers/main.yml` does have a handler with this name which include `./reset_interface.yml`. Some testing showed the import seemed to be the problem; `import_tasks` didn't fix it either.

**Comment by sjpb** [comment]
Note that this appeared to be "fixed" by removing `reset_interface.yml` and moving the code into a block in `configure_ib/handlers/main.yml`. However later the problem reappeared, so I'm not clear on whether it "worked" because the handler wasn't triggered, or there's some other race condition.

**Comment by jovial** [comment]
Sorry, I duplicated this in #95.
